# Generated by Django 5.1 on 2024-08-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_imo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
