# Generated by Django 5.1 on 2024-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_imo', '0002_alter_client_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='numero',
        ),
        migrations.AddField(
            model_name='client',
            name='tel',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
