# Generated by Django 5.1 on 2024-08-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_imo', '0003_remove_client_cni_remove_client_numero_client_tel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('num_cni', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
    ]
