# Generated by Django 5.1 on 2024-08-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_imo', '0005_bienimmobilier_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bien_immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.bienimmobilier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.achats')),
                ('bien_immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.bienimmobilier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges_imo.location')),
            ],
        ),
    ]
